# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ed Cupaioli
email: your-email@domain.com
description: Frontend Developer | Web Designer
url: https://edcupaioli.com # the base hostname & protocol for your site, e.g. http://example.com
meta_img: ""
github_username:  ecupaio
repo: "personal-site"
future: true

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-admin
  - uglifier
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
sass:
  sass_dir: _sass
  style: compressed
# Collections
collections:
  projects:
    output: true
    permalink: /project/:title/
  experience:
    output: true
  skills:
    output: true
defaults:
  -
    scope:
      path: ""
    values:
      layout: "index"
prose:
  ignore: ['_layouts','_plugins']
  metadata:
    _projects:
      - name: "link"
        field:
          element: "text"
          label: "Link"
          help: "URL for project"
          value: ""
          placeholder: "Helper text in the input if no value is provided."
          type: "text"
      - name: "img"
        field:
          element: "multiselect"
          label: "Image"
          help: "Image for project"
          value: ""
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Date of project release"
          value: ""
          type: "text"
      - name: "tech"
        field:
          element: "multiselect"
          label: "Tech"
          help: "List tech used for project"
          alterable: true
          value: ""
          options:
            - name: "Jekyll"
              value: "Jekyll"
            - name: "Blue State Digital"
              value: "Blue State Digital"  
