# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ed Cupaioli
description: Web Developer | Full-Stack UX Designer
url: https://edcupaioli.com # the base hostname & protocol for your site, e.g. http://example.com
meta_img: ""
gtm: 'GTM-THQC7Q9'
future: true
timezone: "America/New_York"
# Build settings
markdown: kramdown
include: ['_pages']
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
sass:
  sass_dir: _sass
  style: compressed
livereload: true
# Collections
collections:
  projects:
    output: true
    permalink: /project/:title/
  experience:
    output: true
    test: ""
  skills:
    output: true
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "projects"
    values:
      link: ""
      img:
        - ""
      tech:
        - ""
      date: "2017-01-01"
  -
    scope:
      type: "posts"
    values:
      permalink: "/blog/:title/"
      layout: "blog-post"
      tags:
        - ""
