title: Ed Cupaioli
description: Web Development | Analytics | Product Management
url: https://edcupaioli.com 
meta_img: "/images/ec-meta-img.png"
email: "ed.cupaioli@gmail.com"
phone: 469-867-3438
favicon: "/images/favicon.png"
org-name: Ed Cupaioli LLC
first-name: Ed
last-name: Cupaioli
address: 2630 32nd St
city: Sacramento 
state: CA
zip: 95817
social: 
- https://www.linkedin.com/in/ed-cupaioli-10a9849/
- https://github.com/ecupaio
gtm: 'GTM-THQC7Q9'
future: true
timezone: "America/New_York"
# Build settings
markdown: kramdown
include: ['_pages']
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
sass:
  sass_dir: _sass
  style: compressed
livereload: true
# Collections
collections:
  projects:
    output: true
    layout: project
    permalink: /project/:title/
  experience:
    output: false
  skills:
    output: true
  services: 
    output: true
    permalink: /service/:title/  
  studies: 
    output: true
    permalink: /study/:title/   
  redirects:
    output: true
    layout: redirect  
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      type: "projects"
    values:
      link: ""
      published: false
      img:
        - ""
      tech:
        - ""
      date: "2017-01-01"
      layout: "project"
  - scope:
      type: "posts"
    values:
      permalink: "/blog/:title/"
      layout: "blog-post"
      published: false
      tags:
        - ""
  - scope: 
      type: "services"      
    values: 
      layout: service  
  - scope: 
      type: "studies"      
    values: 
      layout: study
  - scope: 
      type: "redirects"      
    values: 
      layout: redirect          
picture:
  source: ""
  output: "images/generated/"
  ignore_missing_images: true
  webp: 
    format: webp