collections_config:
  posts:
    name: Posts
    path: _posts
    add_options: 
    - name: Add Post
      editor: content
      schema: default
    schemas:
      default: 
        path: .cloudcannon/schemas/post.md
        name: Blog Post
        _enabled_editors:
          - content
        _inputs:
          $.meta_img:
            label: Meta Image
          $.tags:
            type: multiselect
            options:
              values: []
              allow_create: true
              allow_empty: true
          date:
            instance_value: NOW   
          published: 
            type: switch
  drafts:
    path: _drafts
    output: false
    create:
      publish_to: posts
    _inputs: 
      $.published: 
        type: switch
  projects:
    name: Projects
    path: _projects
    schemas:
      default:
        path: .cloudcannon/schemas/project.md
        name: Project
        _enabled_editors:
          - content
        _inputs:
          $.image[*]:
            type: image
          $.image:
            type: array
          $.tech:
            type: array
          $.layout:
            hidden: true
          published: 
            type: switch  
  experience:
    name: Experience
    path: _experience
    schemas:
      default:
        path: .cloudcannon/schemas/experience.md
        name: Experience
        _enabled_editors:
          - content
        _inputs:
          $.org_logo:
            type: file
          projects:  
            type: select
            options: 
              values: collections.projects
              value_key: path
  skills:
    name: Skills
    path: _skills
  pages:
    name: Pages
    path: _pages

collection_groups:
  - heading: Content
    collections:
      - posts
      - drafts
      - projects
      - experience
      - skills
      - pages
paths:
  static: ''
  uploads: images



_inputs:
  template:
    hidden: true
  css: 
    hidden: true
  date:
    instance_value: NOW
timezone: America/Los_Angeles

_editables:
  content:
    bold: true
    italic: true
    bulletedlist: true
    numberedlist: true
    image: true
    table: true
    undo: true
    redo: true
  
    