collections_config:
  posts:
    name: Posts
    path: _posts
    add_options: 
    - name: Add Post
      editor: content
    - name: Add Draft
      editor: content
      collection: drafts
      schema: default  
    schemas:
      blog-post: 
        path: .cloudcannon/schemas/post.md
        name: Blog Post
        _enabled_editors:
          - content
        _inputs:
          $.meta_img:
            label: Meta Image
          $.tags:
            type: multiselect
            options:
              values: []
              allow_create: true
              allow_empty: true
  drafts:
    path: _drafts
    output: false
    create:
      publish_to: posts
  projects:
    name: Projects
    path: _projects
    schemas:
      default:
        path: .cloudcannon/schemas/project.md
        name: Project
        _enabled_editors:
          - content
        _inputs:
          $.image[*]:
            type: image
          $.image:
            type: array
          $.tech:
            type: array
          $.layout:
            hidden: true
  experience:
    name: Experience
    path: _experience
    schemas:
      default:
        path: .cloudcannon/schemas/experience.md
        name: Experience
        _enabled_editors:
          - content
        _inputs:
          $.org_logo:
            type: file
  skills:
    name: Skills
    path: _skills
  pages:
    name: Pages
    path: _pages

collection_groups:
  - heading: Content
    collections:
      - posts
      - projects
      - experience
      - skills
      - pages
paths:
  static: ''
  uploads: images



_inputs:
  template:
    hidden: true
  css: 
    hidden: true
  
    