collections_config:
  data: 
    name: Menus
    path: _data
  posts:
    name: Posts
    path: _posts
    add_options: 
    - name: Add Post
      editor: content
      schema: default
    schemas:
      default: 
        path: .cloudcannon/schemas/post.md
        name: Blog Post
        _enabled_editors:
          - content
        _inputs:
          $.meta_img:
            label: Meta Image
          $.tags:
            type: multiselect
            options:
              values: []
              allow_create: true
              allow_empty: true
          date:
            instance_value: NOW   
          published: 
            type: switch
  drafts:
    path: _drafts
    output: false
    create:
      publish_to: posts
    _inputs: 
      $.published: 
        type: switch
  projects:
    name: Projects
    path: _projects
    schemas:
      default:
        path: .cloudcannon/schemas/project.md
        name: Project
        _enabled_editors:
          - content
        _inputs:
          $.image[*]:
            type: image
          $.image:
            type: array
          $.tech:
            type: array
          $.layout:
            hidden: true
          published: 
            type: switch  
  experience:
    name: Experience
    path: _experience
    schemas:
      default:
        path: .cloudcannon/schemas/experience.md
        name: Experience
        _enabled-editors:
          - data
        _inputs:
          $.org_logo:
            type: image
          projects:  
            type: multiselect
            options: 
              values: collections.projects
              value_key: path
  skills:
    name: Skills
    path: _skills
  pages:
    name: Pages
    path: _pages

collection_groups:
  - heading: Content
    collections:
      - posts
      - drafts
      - projects
      - experience
      - skills
      - pages
      - data
paths:
  static: ''
  uploads: images



_inputs:
  template:
    hidden: true
  css: 
    hidden: true
  date:
    instance_value: NOW
timezone: America/Los_Angeles

_editables:
  text:
    italic: true
  block:
    format: p h3
    undo: true
    redo: true
  content:
    blockquote: true
    bold: true
    format: p h1 h2 h3 h4 h5 h6 pre address div
    italic: true
    strike: true
    subscript: true
    superscript: true
    underline: true
    link: true
    bulletedlist: true
    indent: true
    numberedlist: true
    outdent: true
    code: true
    embed: true
    horizontalrule: true
    image: true
    table: true
    undo: true
    redo: true
    removeformat: true
    copyformatting: true
    styles: /css/editor.css
    left: align-left
    center: align-center
    right: align-right
    justify: align-justify
    image_size_attributes: true
    snippet: true
     
  
    