collections_config:
  blog-posts:
    name: Blog posts
    path: _posts
    schemas:
      blog-post: &ref_0
        path: .cloudcannon/schemas/blog-post.md
        name: Blog Post
        _enabled_editors:
          - content
        _inputs:
          $.meta_img:
            label: Meta Image
          $.tags:
            type: multiselect
            options:
              values: []
              allow_create: true
              allow_empty: true
  projects:
    name: Projects
    path: _projects
    schemas:
      default:
        path: .cloudcannon/schemas/project.md
        name: Project
        _enabled_editors:
          - content
        _inputs:
          $.image[*]:
            type: image
          $.image:
            type: array
          $.tech:
            type: array
          $.layout:
            hidden: true
  experience:
    name: Experience
    path: _experience
    schemas:
      default:
        path: .cloudcannon/schemas/experience.md
        name: Experience
        _enabled_editors:
          - content
        _inputs:
          $.org_logo:
            type: file
  skills:
    name: Skills
    path: _skills
  pages:
    name: Pages
    path: ''
collection_groups:
  - heading: Content
    collections:
      - blog-posts
      - projects
      - experience
      - skills
      - pages
paths:
  static: ''
  uploads: images
_inputs:
  template:
    hidden: true
  css: 
    hidden: true  
