---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: image_gallery
  name: image
  label: image
- type: list
  name: tech
  label: tech
- type: text
  name: link
  label: link
